// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpHZLBJjUhPMKTjkdP3l-oAIS_J6UlsHw',
    appId: '1:960938675095:web:095e91ea8c6eb19efd92d2',
    messagingSenderId: '960938675095',
    projectId: 'spendwise-c7c4b',
    authDomain: 'spendwise-c7c4b.firebaseapp.com',
    storageBucket: 'spendwise-c7c4b.firebasestorage.app',
    measurementId: 'G-72TCNVW6S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClqvVnRwsVUmgixSxLvZRiiWwdkbYADkI',
    appId: '1:960938675095:android:2d7828c991c2ce15fd92d2',
    messagingSenderId: '960938675095',
    projectId: 'spendwise-c7c4b',
    storageBucket: 'spendwise-c7c4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGGeloBwDHGfq9rXnohko_XCjpzeNTb0c',
    appId: '1:960938675095:ios:3bd36e9d9ae2f152fd92d2',
    messagingSenderId: '960938675095',
    projectId: 'spendwise-c7c4b',
    storageBucket: 'spendwise-c7c4b.firebasestorage.app',
    iosBundleId: 'com.example.spendwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGGeloBwDHGfq9rXnohko_XCjpzeNTb0c',
    appId: '1:960938675095:ios:3bd36e9d9ae2f152fd92d2',
    messagingSenderId: '960938675095',
    projectId: 'spendwise-c7c4b',
    storageBucket: 'spendwise-c7c4b.firebasestorage.app',
    iosBundleId: 'com.example.spendwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpHZLBJjUhPMKTjkdP3l-oAIS_J6UlsHw',
    appId: '1:960938675095:web:59ba389bec4ed130fd92d2',
    messagingSenderId: '960938675095',
    projectId: 'spendwise-c7c4b',
    authDomain: 'spendwise-c7c4b.firebaseapp.com',
    storageBucket: 'spendwise-c7c4b.firebasestorage.app',
    measurementId: 'G-YJHL8JXWKS',
  );
}
